const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            image:'assets/images/p1.jpg',
            price:'£120',
            brand:'Nike',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirt',
            image:'assets/images/p1.jpg',
            price:'£100',
            brand:'Adidas',
            rating:'4.5',
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Reebok Slim Shirt',
            image:'assets/images/p1.jpg',
            price:'£150',
            brand:'Reebok',
            rating:'4',
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Lacoste Slim Shirt',
            image:'assets/images/p1.jpg',
            price:'£130',
            brand:'Lacoste',
            rating:'3.5',
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Boss Fit Shirt',
            image:'assets/images/p1.jpg',
            price:'£160',
            brand:'Boss',
            rating:'3.5',
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Zara Fit Shirt',
            image:'assets/images/p1.jpg',
            price:'£100',
            brand:'Zara',
            rating:'4.5',
            numReviews:10,
            description:'high quality product',
        },
    ],
};
export default data;